import type { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    brand: 'ONYX',
    name: 'Pattern Western Wear',
    price: 1299,
    originalPrice: 2598,
    discount: '(50% OFF)',
    imageUrl: '/products/1_Men_WesternWear_T-Shirt_Pattern_Abstract_Blue.png',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in blue, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p2',
    brand: 'FRONTIER',
    name: 'Pattern Western Wear',
    price: 1352,
    originalPrice: 2704,
    discount: '(50% OFF)',
    imageUrl: '/products/2_Men_WesternWear_T-ShirtPattern_Animal_Multicolour,Blue,Brown.png',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in multicolour,blue,brown, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p3',
    brand: 'RUSTLER CO.',
    name: 'Pattern Western Wear',
    price: 1405,
    originalPrice: 2810,
    discount: '(50% OFF)',
    imageUrl: '/products/3_Men_WesternWear_T-Shirt_Pattern_Applique_Blue.png',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in blue, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p4',
    brand: 'METRO UOMO',
    name: 'Pattern Western Wear',
    price: 1458,
    originalPrice: 2916,
    discount: '(50% OFF)',
    imageUrl: '/products/4_Men_WesternWear_T-Shirt_Pattern_Art Deco_Grey.png',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in grey, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p5',
    brand: 'AURA',
    name: 'Pattern Western Wear',
    price: 1511,
    originalPrice: 3022,
    discount: '(50% OFF)',
    imageUrl: '/products/21_Men_WesternWear_T-Shirt_Pattern_Herringbone_Blue.png',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in blue, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p6',
    brand: 'VEXEL',
    name: 'Pattern Western Wear',
    price: 1564,
    originalPrice: 3128,
    discount: '(50% OFF)',
    imageUrl: '/products/22_Men_WesternWear_T-Shirt_Pattern_Holographic_Grey.png',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in grey, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p7',
    brand: 'ECLAT',
    name: 'Pattern Western Wear',
    price: 1617,
    originalPrice: 3234,
    discount: '(50% OFF)',
    imageUrl: '/products/23_Men_WesternWear_T-Shirt_Pattern_Houndstooth_Multicolour_Black_White.png',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in multicolour,black,white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p8',
    brand: 'ZENITH',
    name: 'Pattern Western Wear',
    price: 1670,
    originalPrice: 3340,
    discount: '(50% OFF)',
    imageUrl: '/products/24_Men_WesternWear_T-Shirt_Pattern_Ikat_Blue.png',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in blue, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p9',
    brand: 'INDIGO THREADS',
    name: 'Pattern Western Wear',
    price: 1723,
    originalPrice: 3446,
    discount: '(50% OFF)',
    imageUrl: '/products/25_Men_WesternWear_T-Shirt_Pattern_Indian_Red.png',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in red, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p10',
    brand: 'BASICS+',
    name: 'Fit Western Wear',
    price: 1776,
    originalPrice: 3552,
    discount: '(50% OFF)',
    imageUrl: '/products/69_Men_WesternWear_T-Shirt_Fit_SlimFit_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in  blue, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p11',
    brand: 'ONYX',
    name: 'Fit Western Wear',
    price: 1829,
    originalPrice: 3658,
    discount: '(50% OFF)',
    imageUrl: '/products/70_Men_WesternWear_T-Shirt_Fit_extraSlimFit_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in  blue, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p12',
    brand: 'FRONTIER',
    name: 'Fit Western Wear',
    price: 1882,
    originalPrice: 3764,
    discount: '(50% OFF)',
    imageUrl: '/products/71_Men_WesternWear_T-Shirt_Fit_RegularFit_71.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in white, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p13',
    brand: 'RUSTLER CO.',
    name: 'Fit Western Wear',
    price: 1935,
    originalPrice: 3870,
    discount: '(50% OFF)',
    imageUrl: '/products/73_Men_WesternWear_T-Shirt_Fit_boxyFit_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in blue, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p14',
    brand: 'METRO UOMO',
    name: 'Transparency Western Wear',
    price: 1988,
    originalPrice: 3976,
    discount: '(50% OFF)',
    imageUrl: '/products/81_Men_WesternWear_T-Shirt_Transparency_Opaque_Brown.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in brown, featuring a striking transparency pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p15',
    brand: 'AURA',
    name: 'Transparency Western Wear',
    price: 2041,
    originalPrice: 4082,
    discount: '(50% OFF)',
    imageUrl: '/products/82_Men_WesternWear_T-Shirt_Transparency_Semi-sheer_Black.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in black, featuring a striking transparency pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p16',
    brand: 'VEXEL',
    name: 'Transparency Western Wear',
    price: 2094,
    originalPrice: 4188,
    discount: '(50% OFF)',
    imageUrl: '/products/83_Men_WesternWear_T-Shirt_TransparencySheer_White.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in white, featuring a striking transparency pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p17',
    brand: 'ECLAT',
    name: 'Features Western Wear',
    price: 2147,
    originalPrice: 4294,
    discount: '(50% OFF)',
    imageUrl: '/products/84_Men_WesternWear_T-Shirt_Features_3DChassis_Black.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in black, featuring a striking features pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p18',
    brand: 'ZENITH',
    name: 'Features Western Wear',
    price: 2200,
    originalPrice: 4400,
    discount: '(50% OFF)',
    imageUrl: '/products/85_Men_WesternWear_T-Shirt_Features_Absorbent_Grey.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in grey, featuring a striking features pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p19',
    brand: 'INDIGO THREADS',
    name: 'Features Western Wear',
    price: 2253,
    originalPrice: 4506,
    discount: '(50% OFF)',
    imageUrl: '/products/86_Men_WesternWear_T-Shirt_Features_Activchill_LightGreen.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in lightgreen, featuring a striking features pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p20',
    brand: 'BASICS+',
    name: 'Features Western Wear',
    price: 2306,
    originalPrice: 4612,
    discount: '(50% OFF)',
    imageUrl: '/products/97_Men_WesternWear_T-Shirt_Features_Hooded_Grey.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in grey, featuring a striking features pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p21',
    brand: 'ONYX',
    name: 'Features Western Wear',
    price: 2359,
    originalPrice: 4718,
    discount: '(50% OFF)',
    imageUrl: '/products/108_Men_WesternWear_T-Shirt_Features_Water-proof_Dark_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in dark_blue, featuring a striking features pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p22',
    brand: 'FRONTIER',
    name: 'Features Western Wear',
    price: 2412,
    originalPrice: 4824,
    discount: '(50% OFF)',
    imageUrl: '/products/111_Men_WesternWear_T-Shirt_Features_WrinkleFree_White.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in white, featuring a striking features pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p23',
    brand: 'RUSTLER CO.',
    name: 'Style Type Western Wear',
    price: 2465,
    originalPrice: 4930,
    discount: '(50% OFF)',
    imageUrl: '/products/112_Men_WesternWear_T-Shirt_StyleType_Polo_Dark_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in light_green, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p24',
    brand: 'METRO UOMO',
    name: 'Style Type Western Wear',
    price: 2518,
    originalPrice: 5036,
    discount: '(50% OFF)',
    imageUrl: '/products/113_Men_WesternWear_T-Shirt_Style_Type_V-neck_Black.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in black, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p25',
    brand: 'AURA',
    name: 'Style Type Western Wear',
    price: 2571,
    originalPrice: 5142,
    discount: '(50% OFF)',
    imageUrl: '/products/115_Men_Western Wear_T-Shirt_Style2Type_Crew_Brown.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in brown, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p26',
    brand: 'VEXEL',
    name: 'Style Type Western Wear',
    price: 2624,
    originalPrice: 5248,
    discount: '(50% OFF)',
    imageUrl: '/products/117_Men_WesternWear_T-Shirt_StyleType_Round_Dark_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in dark_blue, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p27',
    brand: 'ECLAT',
    name: 'Style Type Western Wear',
    price: 2677,
    originalPrice: 5354,
    discount: '(50% OFF)',
    imageUrl: '/products/118_Men_WesternWear_T-Shirt_Style_Type_Singlet_Yellow.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in yellow, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p28',
    brand: 'ZENITH',
    name: 'Fabric Type Western Wear',
    price: 2730,
    originalPrice: 5460,
    discount: '(50% OFF)',
    imageUrl: '/products/121_Men_WesternWear_T-Shirt_FabricType_Acrylic_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in blue, featuring a striking fabric type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p29',
    brand: 'INDIGO THREADS',
    name: 'Fabric Type Western Wear',
    price: 2783,
    originalPrice: 5566,
    discount: '(50% OFF)',
    imageUrl: '/products/122_Men_WesternWear_T-Shirt_FabricType_Art Silk_White.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in white, featuring a striking fabric type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p30',
    brand: 'BASICS+',
    name: 'Fabric Type Western Wear',
    price: 2836,
    originalPrice: 5672,
    discount: '(50% OFF)',
    imageUrl: '/products/124_Men_WesternWear_T-Shirt_FabricType_Baluchari_Green.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in dark_blue, featuring a striking fabric type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p31',
    brand: 'ONYX',
    name: 'Fabric Type Western Wear',
    price: 2889,
    originalPrice: 5778,
    discount: '(50% OFF)',
    imageUrl: '/products/125_Men_WesternWear_T-Shirt_FabricType_Bamboo_Green.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in green, featuring a striking fabric type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p32',
    brand: 'FRONTIER',
    name: 'Pattern Night & Loungewear',
    price: 2942,
    originalPrice: 5884,
    discount: '(50% OFF)',
    imageUrl: '/products/235_Men_Night & Loungewear_T-Shirt_Pattern_Abstract_Black.jpeg',
    gender: 'Men',
    category: 'Night & Loungewear',
    description: 'A stylish men night & loungewear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p33',
    brand: 'RUSTLER CO.',
    name: 'Pattern Night & Loungewear',
    price: 2995,
    originalPrice: 5990,
    discount: '(50% OFF)',
    imageUrl: '/products/236_Men_Night&Loungewear_T-Shirt_Pattern_Animal_Multicolour_Green_Grey_Yellow.jpeg',
    gender: 'Men',
    category: 'Night & Loungewear',
    description: 'A stylish men night & loungewear in multicolour,green,grey,yellow, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p34',
    brand: 'METRO UOMO',
    name: 'Pattern Night & Loungewear',
    price: 1348,
    originalPrice: 2696,
    discount: '(50% OFF)',
    imageUrl: '/products/240_Men_Night&Loungewear_T-Shirt_Pattern_Baroque_Black.jpeg',
    gender: 'Men',
    category: 'Night & Loungewear',
    description: 'A stylish men night & loungewear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p35',
    brand: 'AURA',
    name: 'Pattern Night & Loungewear',
    price: 1401,
    originalPrice: 2802,
    discount: '(50% OFF)',
    imageUrl: '/products/242_Men_Night&Loungewear_T-Shirt_Pattern_Camouflage_Green.jpeg',
    gender: 'Men',
    category: 'Night & Loungewear',
    description: 'A stylish men night & loungewear in green, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p36',
    brand: 'VEXEL',
    name: 'Pattern Night & Loungewear',
    price: 1454,
    originalPrice: 2908,
    discount: '(50% OFF)',
    imageUrl: '/products/243_Men_Night&Loungewear_T-Shirt_Pattern_Cartoon_Red.jpeg',
    gender: 'Men',
    category: 'Night & Loungewear',
    description: 'A stylish men night & loungewear in red, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p37',
    brand: 'ECLAT',
    name: 'Pattern Night & Loungewear',
    price: 1507,
    originalPrice: 3014,
    discount: '(50% OFF)',
    imageUrl: '/products/245_Men_Night&Loungewear_T-Shirt_Pattern_Chevrons_Multicolour_White_Blue_Black.jpeg',
    gender: 'Men',
    category: 'Night & Loungewear',
    description: 'A stylish men night & loungewear in multicolour,white,blue,black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p38',
    brand: 'ZENITH',
    name: 'Pattern Night & Loungewear',
    price: 1560,
    originalPrice: 3120,
    discount: '(50% OFF)',
    imageUrl: '/products/246_Men_Night&Loungewear_T-Shirt_Pattern_Colour-block_Multicolour_White_Green.jpeg',
    gender: 'Men',
    category: 'Night & Loungewear',
    description: 'A stylish men night & loungewear in multicolour,white,green, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p39',
    brand: 'INDIGO THREADS',
    name: 'Waist Rise Western Wear',
    price: 1613,
    originalPrice: 3226,
    discount: '(50% OFF)',
    imageUrl: '/products/464_Men_WesternWear_Jeans_WaistRise_HighRise_Dark_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in dark_blue, featuring a striking waist rise pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p40',
    brand: 'BASICS+',
    name: 'Waist Rise Western Wear',
    price: 1666,
    originalPrice: 3332,
    discount: '(50% OFF)',
    imageUrl: '/products/465_Men_WesternWear_Jeans_WaistRise_MidRise_Dark_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in dark_blue, featuring a striking waist rise pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p41',
    brand: 'ONYX',
    name: 'Waist Rise Western Wear',
    price: 1719,
    originalPrice: 3438,
    discount: '(50% OFF)',
    imageUrl: '/products/466_Men_WesternWear_Jeans_WaistRise_LowRise_Light_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in light_blue, featuring a striking waist rise pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p42',
    brand: 'FRONTIER',
    name: 'Style Type Western Wear',
    price: 1772,
    originalPrice: 3544,
    discount: '(50% OFF)',
    imageUrl: '/products/468_Men_WesternWear_Jeans_StyleType_Flared_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in blue, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p43',
    brand: 'RUSTLER CO.',
    name: 'Style Type Western Wear',
    price: 1825,
    originalPrice: 3650,
    discount: '(50% OFF)',
    imageUrl: '/products/469_Men_WesternWear_Jeans_StyleType_Joggers_Grey.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in grey, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p44',
    brand: 'METRO UOMO',
    name: 'Style Type Western Wear',
    price: 1878,
    originalPrice: 3756,
    discount: '(50% OFF)',
    imageUrl: '/products/470_Men_WesternWear_Jeans_StyleType_Relaxed_Light_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in light_blue, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p45',
    brand: 'AURA',
    name: 'Style Type Western Wear',
    price: 1931,
    originalPrice: 3862,
    discount: '(50% OFF)',
    imageUrl: '/products/471_Men_WesternWear_Jeans_StyleType_Skinny_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in blue, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p46',
    brand: 'VEXEL',
    name: 'Style Type Western Wear',
    price: 1984,
    originalPrice: 3968,
    discount: '(50% OFF)',
    imageUrl: '/products/472_Men_WesternWear_Jeans_StyleType_Slim_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in blue, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p47',
    brand: 'ECLAT',
    name: 'Style Type Western Wear',
    price: 2037,
    originalPrice: 4074,
    discount: '(50% OFF)',
    imageUrl: '/products/473_Men_WesternWear_Jeans_StyleType_Straight_Black.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in black, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p48',
    brand: 'ZENITH',
    name: 'Style Type Western Wear',
    price: 2090,
    originalPrice: 4180,
    discount: '(50% OFF)',
    imageUrl: '/products/474_Men_WesternWear_Jeans_Style_Type_Tapered_Black.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in black, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p49',
    brand: 'INDIGO THREADS',
    name: 'Style Type Western Wear',
    price: 2143,
    originalPrice: 4286,
    discount: '(50% OFF)',
    imageUrl: '/products/476_Men_WesternWear_Jeans_StyleType_Baggy_Light_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in light_blue, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p50',
    brand: 'BASICS+',
    name: 'Style Type Western Wear',
    price: 2196,
    originalPrice: 4392,
    discount: '(50% OFF)',
    imageUrl: '/products/477_Men_WesternWear_Jeans_StyleType_Bootcut_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in blue, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p51',
    brand: 'ONYX',
    name: 'Style Type Western Wear',
    price: 2249,
    originalPrice: 4498,
    discount: '(50% OFF)',
    imageUrl: '/products/479_Men_WesternWear_Jeans_StyleType_Dad_Light_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in light_blue, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p52',
    brand: 'FRONTIER',
    name: 'Distressed Western Wear',
    price: 2302,
    originalPrice: 4604,
    discount: '(50% OFF)',
    imageUrl: '/products/480_Men_WesternWear_Jeans_Distressed_LightDistress_Light_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in light_blue, featuring a striking distressed pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p53',
    brand: 'RUSTLER CO.',
    name: 'Distressed Western Wear',
    price: 2355,
    originalPrice: 4710,
    discount: '(50% OFF)',
    imageUrl: '/products/481_Men_WesternWear_Jeans_Distressed_MidDistress_Light_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in light_blue, featuring a striking distressed pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p54',
    brand: 'METRO UOMO',
    name: 'Distressed Western Wear',
    price: 2408,
    originalPrice: 4816,
    discount: '(50% OFF)',
    imageUrl: '/products/482_Men_WesternWear_Jeans_Distressed_HeavyDistress_Light_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in light_blue, featuring a striking distressed pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p55',
    brand: 'AURA',
    name: 'Distressed Western Wear',
    price: 2461,
    originalPrice: 4922,
    discount: '(50% OFF)',
    imageUrl: '/products/483_Men_WesternWear_Jeans_DistressedClean_Dark_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in dark_blue, featuring a striking distressed pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p56',
    brand: 'VEXEL',
    name: 'Distressed Western Wear',
    price: 2514,
    originalPrice: 5028,
    discount: '(50% OFF)',
    imageUrl: '/products/484_Men_WesternWear_Jeans_Distressed_Kneeslit_Light_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in light_blue, featuring a striking distressed pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p57',
    brand: 'ECLAT',
    name: 'Pattern Western Wear',
    price: 2567,
    originalPrice: 5134,
    discount: '(50% OFF)',
    imageUrl: '/products/491_Men_WesternWear_Shirt_Pattern_BlockPrint_Yellow.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in yellow, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p58',
    brand: 'ZENITH',
    name: 'Pattern Western Wear',
    price: 2620,
    originalPrice: 5240,
    discount: '(50% OFF)',
    imageUrl: '/products/494_Men_Western_Wear_Shirt_Pattern_Checks_Pink.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in pink, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p59',
    brand: 'INDIGO THREADS',
    name: 'Pattern Western Wear',
    price: 2673,
    originalPrice: 5346,
    discount: '(50% OFF)',
    imageUrl: '/products/495_Men_WesternWear_Shirt_Pattern_Chevrons_blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in blue, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p60',
    brand: 'BASICS+',
    name: 'Pattern Western Wear',
    price: 2726,
    originalPrice: 5452,
    discount: '(50% OFF)',
    imageUrl: '/products/501_Men_Western_Wear_Shirt_Pattern_Floral_Multicolour_Green_Red_Yellow.png',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in multicolour,green,red,yellow, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p61',
    brand: 'ONYX',
    name: 'Pattern Western Wear',
    price: 2779,
    originalPrice: 5558,
    discount: '(50% OFF)',
    imageUrl: '/products/503_Men_WesternWear_Shirt_Pattern_Heathered_Multicolour_Blue_White_Black.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in multicolour,blue,white,black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p62',
    brand: 'FRONTIER',
    name: 'Pattern Western Wear',
    price: 2832,
    originalPrice: 5664,
    discount: '(50% OFF)',
    imageUrl: '/products/524_Men_WesternWear_Shirt_Pattern_Reptilian_Dark_Reality.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in dark_red, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p63',
    brand: 'RUSTLER CO.',
    name: 'Pattern Western Wear',
    price: 2885,
    originalPrice: 5770,
    discount: '(50% OFF)',
    imageUrl: '/products/526_Men_WesternWear_Shirt_Pattern_Selfdesign_Grey.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in grey, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p64',
    brand: 'METRO UOMO',
    name: 'Pattern Western Wear',
    price: 2938,
    originalPrice: 5876,
    discount: '(50% OFF)',
    imageUrl: '/products/527_Men_WesternWear_Shirt_Pattern_Solid_Pink.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in pink, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p65',
    brand: 'AURA',
    name: 'Pattern Western Wear',
    price: 2991,
    originalPrice: 5982,
    discount: '(50% OFF)',
    imageUrl: '/products/542_Men_WesternWear_Shirt_Pattern_Movies&Music_White.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p66',
    brand: 'VEXEL',
    name: 'Fit Western Wear',
    price: 1344,
    originalPrice: 2688,
    discount: '(50% OFF)',
    imageUrl: '/products/553_WesternWear_Shirt_Fit_SlimFit_White.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in white, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p67',
    brand: 'ECLAT',
    name: 'Fit Western Wear',
    price: 1397,
    originalPrice: 2794,
    discount: '(50% OFF)',
    imageUrl: '/products/554_Men_WesternWear_Shirt_Fit_ExtraSlimFit_Brown.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in brown, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p68',
    brand: 'ZENITH',
    name: 'Fit Western Wear',
    price: 1450,
    originalPrice: 2900,
    discount: '(50% OFF)',
    imageUrl: '/products/555_Men_WesternWear_Shirt_Fit_RegularFit_Blue.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in blue, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p69',
    brand: 'INDIGO THREADS',
    name: 'Fit Western Wear',
    price: 1503,
    originalPrice: 3006,
    discount: '(50% OFF)',
    imageUrl: '/products/559_Men_WesternWear_Shirt_Fit_LooseFit_Brown.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in brown, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p70',
    brand: 'BASICS+',
    name: 'Fit Western Wear',
    price: 1556,
    originalPrice: 3112,
    discount: '(50% OFF)',
    imageUrl: '/products/562_Men_WesternWear_Shirt_Fit_AthleticFit_Multicolour_Black_White.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in white, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p71',
    brand: 'ONYX',
    name: 'Pattern Night & Loungewear',
    price: 1609,
    originalPrice: 3218,
    discount: '(50% OFF)',
    imageUrl: '/products/565_Men_Night&Loungewear_Co-ordSet_Pattern_Abstract_Multicolour_Black_White.jpeg',
    gender: 'Men',
    category: 'Night & Loungewear',
    description: 'A stylish men night & loungewear in multicolour,black,white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p72',
    brand: 'FRONTIER',
    name: 'Pattern Night & Loungewear',
    price: 1662,
    originalPrice: 3324,
    discount: '(50% OFF)',
    imageUrl: '/products/566_Men_Night&Loungewear_Co-ordSet_Pattern_Animal_Multicolour_Black_Purple.jpeg',
    gender: 'Men',
    category: 'Night & Loungewear',
    description: 'A stylish men night & loungewear in multicolour,black,purple, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p73',
    brand: 'RUSTLER CO.',
    name: 'Pattern Night & Loungewear',
    price: 1715,
    originalPrice: 3430,
    discount: '(50% OFF)',
    imageUrl: '/products/568_Men_Night&Loungewear_Co-ordSet_Pattern_ArtDeco_Multicolour_Black_White.jpeg',
    gender: 'Men',
    category: 'Night & Loungewear',
    description: 'A stylish men night & loungewear in multicolour,black,white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p74',
    brand: 'METRO UOMO',
    name: 'Pattern Night & Loungewear',
    price: 1768,
    originalPrice: 3536,
    discount: '(50% OFF)',
    imageUrl: '/products/569_Men_Night&Loungewear_Co-ordSet_Pattern_Aztec_Brown.jpeg',
    gender: 'Men',
    category: 'Night & Loungewear',
    description: 'A stylish men night & loungewear in brown, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p75',
    brand: 'AURA',
    name: 'Pattern Night & Loungewear',
    price: 1821,
    originalPrice: 3642,
    discount: '(50% OFF)',
    imageUrl: '/products/580_Men_Night&Loungewear_Co-ordSet_Pattern_Embroidery_Green.jpeg',
    gender: 'Men',
    category: 'Night & Loungewear',
    description: 'A stylish men night & loungewear in green, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p76',
    brand: 'VEXEL',
    name: 'Style Type Night & Loungewear',
    price: 1874,
    originalPrice: 3748,
    discount: '(50% OFF)',
    imageUrl: '/products/633_Men_Night&Loungewear_Co-ordSet_StyleType_3-Piece Sets_Brown.jpeg',
    gender: 'Men',
    category: 'Night & Loungewear',
    description: 'A stylish men night & loungewear in brown, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p77',
    brand: 'ECLAT',
    name: 'Style Type Night & Loungewear',
    price: 1927,
    originalPrice: 3854,
    discount: '(50% OFF)',
    imageUrl: '/products/634_Men Night&Loungewear_Co-ordSet_StyleType_2-Piece Sets_White.jpeg',
    gender: 'Men',
    category: 'Night & Loungewear',
    description: 'A stylish men night & loungewear in white, featuring a striking style type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p78',
    brand: 'ZENITH',
    name: 'Pattern Western Wear',
    price: 1980,
    originalPrice: 3960,
    discount: '(50% OFF)',
    imageUrl: '/products/643_Men_WesternWear_Blazers&Waistcoats_Pattern_Camouflage_Green.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in green, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p79',
    brand: 'INDIGO THREADS',
    name: 'Pattern Western Wear',
    price: 2033,
    originalPrice: 4066,
    discount: '(50% OFF)',
    imageUrl: '/products/652_Men_WesternWear_Blazers&Waistcoats_Pattern_Floral_Red.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in red, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p80',
    brand: 'BASICS+',
    name: 'Pattern Western Wear',
    price: 2086,
    originalPrice: 4172,
    discount: '(50% OFF)',
    imageUrl: '/products/654_Men_WesternWear_Blazers&Waistcoats_Pattern_Graphic_Yellow.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in yellow, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p81',
    brand: 'ONYX',
    name: 'Pattern Western Wear',
    price: 2139,
    originalPrice: 4278,
    discount: '(50% OFF)',
    imageUrl: '/products/655_Men_WesternWear_Blazers&Waistcoats_Pattern_Heathered_White.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p82',
    brand: 'FRONTIER',
    name: 'Pattern Western Wear',
    price: 2192,
    originalPrice: 4384,
    discount: '(50% OFF)',
    imageUrl: '/products/683_Men_WesternWear_Blazers&Waistcoats_Pattern_Stripes_Black.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p83',
    brand: 'RUSTLER CO.',
    name: 'Pattern Western Wear',
    price: 2245,
    originalPrice: 4490,
    discount: '(50% OFF)',
    imageUrl: '/products/684_Men_WesternWear_Blazers_&_Waistcoats_Pattern_Superhero_Red.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in red, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p84',
    brand: 'METRO UOMO',
    name: 'Pattern Western Wear',
    price: 2298,
    originalPrice: 4596,
    discount: '(50% OFF)',
    imageUrl: '/products/701_Men_WesternWear_Blazers&Waistcoats_Pattern_Patchwork_Green.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in green, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p85',
    brand: 'AURA',
    name: 'Fit Western Wear',
    price: 2351,
    originalPrice: 4702,
    discount: '(50% OFF)',
    imageUrl: '/products/704_Men_WesternWea_Blazers&Waistcoats_Fit_SlimFit_Black.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in black, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p86',
    brand: 'VEXEL',
    name: 'Fit Western Wear',
    price: 2404,
    originalPrice: 4808,
    discount: '(50% OFF)',
    imageUrl: '/products/705_Grey_Men_WesternWear_Blazers&Waistcoats_Fit_ExtraSlimFit_Grey.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in grey, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p87',
    brand: 'ECLAT',
    name: 'Fit Western Wear',
    price: 2457,
    originalPrice: 4914,
    discount: '(50% OFF)',
    imageUrl: '/products/706_Men_WesternWear_Blazers&Waistcoats_Fit_Regular_Fit_White.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in white, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p88',
    brand: 'ZENITH',
    name: 'Fit Western Wear',
    price: 2510,
    originalPrice: 5020,
    discount: '(50% OFF)',
    imageUrl: '/products/708_Men_Western_Wear_Blazers&Waistcoats_Fit_BoxyFit_Brown.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in brown, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p89',
    brand: 'INDIGO THREADS',
    name: 'Fit Western Wear',
    price: 2563,
    originalPrice: 5126,
    discount: '(50% OFF)',
    imageUrl: '/products/711_Men_WesternWear_Blazers&Waistcoats_Fit_RelaxedFit_Brown.jpeg',
    gender: 'Men',
    category: 'Western Wear',
    description: 'A stylish men western wear in brown, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p90',
    brand: 'BASICS+',
    name: 'Pattern Inner Wear',
    price: 2616,
    originalPrice: 5232,
    discount: '(50% OFF)',
    imageUrl: '/products/759_Men_InnerWear_Boxers_Pattern_Selfdesign_Black.jpeg',
    gender: 'Men',
    category: 'Inner Wear',
    description: 'A stylish men inner wear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p91',
    brand: 'ONYX',
    name: 'Pattern Inner Wear',
    price: 2669,
    originalPrice: 5338,
    discount: '(50% OFF)',
    imageUrl: '/products/760_Men_InnerWear_Boxers_Pattern-Solid_Grey.jpeg',
    gender: 'Men',
    category: 'Inner Wear',
    description: 'A stylish men inner wear in grey, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p92',
    brand: 'FRONTIER',
    name: 'Distressed Western Wear',
    price: 2722,
    originalPrice: 5444,
    discount: '(50% OFF)',
    imageUrl: '/products/2909_Women_WesternWear_Jeans_Distressed_Clean_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in blue, featuring a striking distressed pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p93',
    brand: 'RUSTLER CO.',
    name: 'Distressed Western Wear',
    price: 2775,
    originalPrice: 5550,
    discount: '(50% OFF)',
    imageUrl: '/products/2909_Women_WesternWear_Jeans_Distressed_Clean_blue.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking distressed pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p94',
    brand: 'METRO UOMO',
    name: 'Distressed Western Wear',
    price: 2828,
    originalPrice: 5656,
    discount: '(50% OFF)',
    imageUrl: '/products/2909_Women_WesternWear_Jeans_Distressed_Clean_red.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking distressed pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p95',
    brand: 'AURA',
    name: 'Distressed Western Wear',
    price: 2881,
    originalPrice: 5762,
    discount: '(50% OFF)',
    imageUrl: '/products/2909_Women_WesternWear_Jeans_Distressed_Clean_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in red, featuring a striking distressed pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p96',
    brand: 'VEXEL',
    name: 'Distressed Western Wear',
    price: 2934,
    originalPrice: 5868,
    discount: '(50% OFF)',
    imageUrl: '/products/2910_Women_WesternWear_Jeans_Distressed_LightDistress_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in blue, featuring a striking distressed pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p97',
    brand: 'ECLAT',
    name: 'Distressed Western Wear',
    price: 2987,
    originalPrice: 5974,
    discount: '(50% OFF)',
    imageUrl: '/products/2910_Women_WesternWear_Jeans_Distressed_LightDistress_blue.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking distressed pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p98',
    brand: 'ZENITH',
    name: 'Distressed Western Wear',
    price: 1340,
    originalPrice: 2680,
    discount: '(50% OFF)',
    imageUrl: '/products/2910_Women_WesternWear_Jeans_Distressed_LightDistress_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking distressed pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p99',
    brand: 'INDIGO THREADS',
    name: 'Fit Western Wear',
    price: 1393,
    originalPrice: 2786,
    discount: '(50% OFF)',
    imageUrl: '/products/3383_Women Western Wear Jeans Fit Skinny blue.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in blue, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p100',
    brand: 'BASICS+',
    name: 'Fit Western Wear',
    price: 1446,
    originalPrice: 2892,
    discount: '(50% OFF)',
    imageUrl: '/products/3383_Women_WesternWear_Jeans_Fit_Skinny_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p101',
    brand: 'ONYX',
    name: 'Fit Western Wear',
    price: 1499,
    originalPrice: 2998,
    discount: '(50% OFF)',
    imageUrl: '/products/3383_Women_WesternWear_Jeans_Fit_Skinny_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p102',
    brand: 'FRONTIER',
    name: 'Fit Western Wear',
    price: 1552,
    originalPrice: 3104,
    discount: '(50% OFF)',
    imageUrl: '/products/3384_Women_WesternWear_Jeans_Fit_SuperSkinny_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p103',
    brand: 'RUSTLER CO.',
    name: 'Fit Western Wear',
    price: 1605,
    originalPrice: 3210,
    discount: '(50% OFF)',
    imageUrl: '/products/3384_Women_WesternWear_Jeans_Fit_SuperSkinny_blue.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p104',
    brand: 'METRO UOMO',
    name: 'Fit Western Wear',
    price: 1658,
    originalPrice: 3316,
    discount: '(50% OFF)',
    imageUrl: '/products/3384_Women_WesternWear_Jeans_Fit_SuperSkinny_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in blue, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p105',
    brand: 'AURA',
    name: 'Fit Western Wear',
    price: 1711,
    originalPrice: 3422,
    discount: '(50% OFF)',
    imageUrl: '/products/3387_Women_WesternWear_Jeans_Fit_Bootcut_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in blue, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p106',
    brand: 'VEXEL',
    name: 'Fit Western Wear',
    price: 1764,
    originalPrice: 3528,
    discount: '(50% OFF)',
    imageUrl: '/products/3387_Women_WesternWear_Jeans_Fit_Bootcut_blue.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p107',
    brand: 'ECLAT',
    name: 'Fit Western Wear',
    price: 1817,
    originalPrice: 3634,
    discount: '(50% OFF)',
    imageUrl: '/products/3387_Women_WesternWear_Jeans_Fit_Bootcut_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p108',
    brand: 'ZENITH',
    name: 'Fit Western Wear',
    price: 1870,
    originalPrice: 3740,
    discount: '(50% OFF)',
    imageUrl: '/products/3389_Women_WesternWear_Jeans_Fit_Wide_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in blue, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p109',
    brand: 'INDIGO THREADS',
    name: 'Fit Western Wear',
    price: 1923,
    originalPrice: 3846,
    discount: '(50% OFF)',
    imageUrl: '/products/3389_Women_WesternWear_Jeans_Fit_Wide_blue.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p110',
    brand: 'BASICS+',
    name: 'Fit Western Wear',
    price: 1976,
    originalPrice: 3952,
    discount: '(50% OFF)',
    imageUrl: '/products/3389_Women_WesternWear_Jeans_Fit_Wide_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p111',
    brand: 'ONYX',
    name: 'Pattern Ethnic Wear',
    price: 2029,
    originalPrice: 4058,
    discount: '(50% OFF)',
    imageUrl: '/products/4001_Women_EthnicWear_Sarees_Pattern_Abstract_Black.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in multicolor, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p112',
    brand: 'FRONTIER',
    name: 'Pattern Ethnic Wear',
    price: 2082,
    originalPrice: 4164,
    discount: '(50% OFF)',
    imageUrl: '/products/4001_Women_EthnicWear_Sarees_Pattern_Abstract_Multicolor.png',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in red, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p113',
    brand: 'RUSTLER CO.',
    name: 'Pattern Ethnic Wear',
    price: 2135,
    originalPrice: 4270,
    discount: '(50% OFF)',
    imageUrl: '/products/4001_Women_EthnicWear_Sarees_Pattern_Abstract_Red.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p114',
    brand: 'METRO UOMO',
    name: 'Pattern Ethnic Wear',
    price: 2188,
    originalPrice: 4376,
    discount: '(50% OFF)',
    imageUrl: '/products/4001_Women_EthnicWear_Sarees_Pattern_Abstract_White.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p115',
    brand: 'AURA',
    name: 'Pattern Ethnic Wear',
    price: 2241,
    originalPrice: 4482,
    discount: '(50% OFF)',
    imageUrl: '/products/4012_Women_EthnicWear_Sarees_Pattern_Colourblock_black.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p116',
    brand: 'VEXEL',
    name: 'Pattern Ethnic Wear',
    price: 2294,
    originalPrice: 4588,
    discount: '(50% OFF)',
    imageUrl: '/products/4012_Women_EthnicWear_Sarees_Pattern_Colourblock_gold.png',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p117',
    brand: 'ECLAT',
    name: 'Pattern Ethnic Wear',
    price: 2347,
    originalPrice: 4694,
    discount: '(50% OFF)',
    imageUrl: '/products/4012_Women_EthnicWear_Sarees_Pattern_Colourblock_multicolor.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in gold, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p118',
    brand: 'ZENITH',
    name: 'Pattern Ethnic Wear',
    price: 2400,
    originalPrice: 4800,
    discount: '(50% OFF)',
    imageUrl: '/products/4012_Women_EthnicWear_Sarees_Pattern_Colourblock_white.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in multicolor, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p119',
    brand: 'INDIGO THREADS',
    name: 'Pattern Ethnic Wear',
    price: 2453,
    originalPrice: 4906,
    discount: '(50% OFF)',
    imageUrl: '/products/4017_Women Ethnic WearSareesPatternEmbellished Black.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p120',
    brand: 'BASICS+',
    name: 'Pattern Ethnic Wear',
    price: 2506,
    originalPrice: 5012,
    discount: '(50% OFF)',
    imageUrl: '/products/4017_Women Ethnic Wear_Sarees_Pattern_Embellished_Blue.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p121',
    brand: 'ONYX',
    name: 'Pattern Ethnic Wear',
    price: 2559,
    originalPrice: 5118,
    discount: '(50% OFF)',
    imageUrl: '/products/4017_Women Ethnic Wear_Sarees_Pattern_Embellished_Multicolor.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in red, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p122',
    brand: 'FRONTIER',
    name: 'Pattern Ethnic Wear',
    price: 2612,
    originalPrice: 5224,
    discount: '(50% OFF)',
    imageUrl: '/products/4017_Women Ethnic Wear_Sarees_Pattern_Embellished_White.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in multicolor, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p123',
    brand: 'RUSTLER CO.',
    name: 'Pattern Ethnic Wear',
    price: 2665,
    originalPrice: 5330,
    discount: '(50% OFF)',
    imageUrl: '/products/4020_Women_EthnicWear_Sarees_Pattern_Floral_Black.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p124',
    brand: 'METRO UOMO',
    name: 'Pattern Ethnic Wear',
    price: 2718,
    originalPrice: 5436,
    discount: '(50% OFF)',
    imageUrl: '/products/4020_Women_EthnicWear_Sarees_Pattern_Floral_Multicolor.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p125',
    brand: 'AURA',
    name: 'Pattern Ethnic Wear',
    price: 2771,
    originalPrice: 5542,
    discount: '(50% OFF)',
    imageUrl: '/products/4020_Women_EthnicWear_Sarees_Pattern_Floral_Red.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in red, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p126',
    brand: 'VEXEL',
    name: 'Pattern Ethnic Wear',
    price: 2824,
    originalPrice: 5648,
    discount: '(50% OFF)',
    imageUrl: '/products/4020_Women_EthnicWear_Sarees_Pattern_Floral_White.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in multicolor, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p127',
    brand: 'ECLAT',
    name: 'Pattern Ethnic Wear',
    price: 2877,
    originalPrice: 5754,
    discount: '(50% OFF)',
    imageUrl: '/products/4027_Women_EthnicWear_Sarees_Pattern_Ikat_black.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p128',
    brand: 'ZENITH',
    name: 'Pattern Ethnic Wear',
    price: 2930,
    originalPrice: 5860,
    discount: '(50% OFF)',
    imageUrl: '/products/4027_Women_EthnicWear_Sarees_Pattern_Ikat_blue.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p129',
    brand: 'INDIGO THREADS',
    name: 'Pattern Ethnic Wear',
    price: 2983,
    originalPrice: 5966,
    discount: '(50% OFF)',
    imageUrl: '/products/4027_Women_EthnicWear_Sarees_Pattern_Ikat_white.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in blue, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p130',
    brand: 'BASICS+',
    name: 'Pattern Ethnic Wear',
    price: 1336,
    originalPrice: 2672,
    discount: '(50% OFF)',
    imageUrl: '/products/4034_Women_EthnicWear_Sarees_Pattern_Metallic & Glitter_blue.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p131',
    brand: 'ONYX',
    name: 'Pattern Ethnic Wear',
    price: 1389,
    originalPrice: 2778,
    discount: '(50% OFF)',
    imageUrl: '/products/4034_Women_EthnicWear_Sarees_Pattern_Metallic&Glitter_black.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in multicolor, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p132',
    brand: 'FRONTIER',
    name: 'Pattern Ethnic Wear',
    price: 1442,
    originalPrice: 2884,
    discount: '(50% OFF)',
    imageUrl: '/products/4034_Women_EthnicWear_Sarees_Pattern_Metallic&Glitter_white.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in blue, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p133',
    brand: 'RUSTLER CO.',
    name: 'Pattern Ethnic Wear',
    price: 1495,
    originalPrice: 2990,
    discount: '(50% OFF)',
    imageUrl: '/products/4042_Women_EthnicWear_Sarees_Pattern_Ombredyed_black.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in multicolor, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p134',
    brand: 'METRO UOMO',
    name: 'Pattern Ethnic Wear',
    price: 1548,
    originalPrice: 3096,
    discount: '(50% OFF)',
    imageUrl: '/products/4042_Women_EthnicWear_Sarees_Pattern_Ombredyed_multicolor.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in  black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p135',
    brand: 'AURA',
    name: 'Pattern Ethnic Wear',
    price: 1601,
    originalPrice: 3202,
    discount: '(50% OFF)',
    imageUrl: '/products/4042_Women_EthnicWear_Sarees_Pattern_Ombredyed_red.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in red, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p136',
    brand: 'VEXEL',
    name: 'Pattern Ethnic Wear',
    price: 1654,
    originalPrice: 3308,
    discount: '(50% OFF)',
    imageUrl: '/products/4046_Women_ EthnicWear_Sarees_Pattern_Polkadot_black.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p137',
    brand: 'ECLAT',
    name: 'Pattern Ethnic Wear',
    price: 1707,
    originalPrice: 3414,
    discount: '(50% OFF)',
    imageUrl: '/products/4046_Women_EthnicWear_Sarees_Pattern_Polkadot_multicolor.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p138',
    brand: 'ZENITH',
    name: 'Pattern Ethnic Wear',
    price: 1760,
    originalPrice: 3520,
    discount: '(50% OFF)',
    imageUrl: '/products/4046_Women_EthnicWear_Sarees_Pattern_Polkadot_red.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in red, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p139',
    brand: 'INDIGO THREADS',
    name: 'Pattern Ethnic Wear',
    price: 1813,
    originalPrice: 3626,
    discount: '(50% OFF)',
    imageUrl: '/products/4046_Women_EthnicWear_Sarees_Pattern_Polkadot_white.jpg',
    gender: 'Women',
    category: 'Ethnic Wear',
    description: 'A stylish women ethnic wear in multicolor, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p140',
    brand: 'BASICS+',
    name: 'Pattern Western Wear',
    price: 1866,
    originalPrice: 3732,
    discount: '(50% OFF)',
    imageUrl: '/products/6833_Women_WesternWear_Top_Pattern_Dyed_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p141',
    brand: 'ONYX',
    name: 'Pattern Western Wear',
    price: 1919,
    originalPrice: 3838,
    discount: '(50% OFF)',
    imageUrl: '/products/6833_Women_WesternWear_Top_Pattern_Dyed_red.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p142',
    brand: 'FRONTIER',
    name: 'Pattern Western Wear',
    price: 1972,
    originalPrice: 3944,
    discount: '(50% OFF)',
    imageUrl: '/products/6833_Women_WesternWear_Top_Pattern_Dyed_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in red, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p143',
    brand: 'RUSTLER CO.',
    name: 'Pattern Western Wear',
    price: 2025,
    originalPrice: 4050,
    discount: '(50% OFF)',
    imageUrl: '/products/6843_Women_WesternWear_Top_Pattern_Lace_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p144',
    brand: 'METRO UOMO',
    name: 'Pattern Western Wear',
    price: 2078,
    originalPrice: 4156,
    discount: '(50% OFF)',
    imageUrl: '/products/6843_Women_WesternWear_Top_Pattern_Lace_red.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p145',
    brand: 'AURA',
    name: 'Pattern Western Wear',
    price: 2131,
    originalPrice: 4262,
    discount: '(50% OFF)',
    imageUrl: '/products/6843_Women_WesternWear_Top_Pattern_Lace_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in red, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p146',
    brand: 'VEXEL',
    name: 'Pattern Western Wear',
    price: 2184,
    originalPrice: 4368,
    discount: '(50% OFF)',
    imageUrl: '/products/6854_Women_WesternWear_Top_Pattern_Solid_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in grey, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p147',
    brand: 'ECLAT',
    name: 'Pattern Western Wear',
    price: 2237,
    originalPrice: 4474,
    discount: '(50% OFF)',
    imageUrl: '/products/6854_Women_WesternWear_Top_Pattern_Solid_grey.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p148',
    brand: 'ZENITH',
    name: 'Pattern Western Wear',
    price: 2290,
    originalPrice: 4580,
    discount: '(50% OFF)',
    imageUrl: '/products/6854_Women_WesternWear_Top_Pattern_Solid_red.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p149',
    brand: 'INDIGO THREADS',
    name: 'Pattern Western Wear',
    price: 2343,
    originalPrice: 4686,
    discount: '(50% OFF)',
    imageUrl: '/products/6854_Women_WesternWear_Top_Pattern_Solid_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in red, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p150',
    brand: 'BASICS+',
    name: 'Pattern Western Wear',
    price: 2396,
    originalPrice: 4792,
    discount: '(50% OFF)',
    imageUrl: '/products/6857_Women_WesternWear_Top_Pattern_Superhero_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p151',
    brand: 'ONYX',
    name: 'Pattern Western Wear',
    price: 2449,
    originalPrice: 4898,
    discount: '(50% OFF)',
    imageUrl: '/products/6857_Women_WesternWear_Top_Pattern_Superhero_blue.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in blue, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p152',
    brand: 'FRONTIER',
    name: 'Pattern Western Wear',
    price: 2502,
    originalPrice: 5004,
    discount: '(50% OFF)',
    imageUrl: '/products/6857_Women_WesternWear_Top_Pattern_Superhero_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p153',
    brand: 'RUSTLER CO.',
    name: 'Pattern Western Wear',
    price: 2555,
    originalPrice: 5110,
    discount: '(50% OFF)',
    imageUrl: '/products/6866_Women_WesternWear_Top_Pattern_Embroidery_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p154',
    brand: 'METRO UOMO',
    name: 'Pattern Western Wear',
    price: 2608,
    originalPrice: 5216,
    discount: '(50% OFF)',
    imageUrl: '/products/6866_Women_WesternWear_Top_Pattern_Embroidery_red.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p155',
    brand: 'AURA',
    name: 'Pattern Western Wear',
    price: 2661,
    originalPrice: 5322,
    discount: '(50% OFF)',
    imageUrl: '/products/6866_Women_WesternWear_Top_Pattern_Embroidery_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in red, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p156',
    brand: 'VEXEL',
    name: 'Pattern Western Wear',
    price: 2714,
    originalPrice: 5428,
    discount: '(50% OFF)',
    imageUrl: '/products/6871_Women_WesternWear_Top_Pattern_Metallic&Glitter_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p157',
    brand: 'ECLAT',
    name: 'Pattern Western Wear',
    price: 2767,
    originalPrice: 5534,
    discount: '(50% OFF)',
    imageUrl: '/products/6871_Women_WesternWear_Top_Pattern_Metallic&Glitter_red.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p158',
    brand: 'ZENITH',
    name: 'Pattern Western Wear',
    price: 2820,
    originalPrice: 5640,
    discount: '(50% OFF)',
    imageUrl: '/products/6871_Women_WesternWear_Top_Pattern_Metallic&Glitter_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in  red, featuring a striking pattern pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p159',
    brand: 'INDIGO THREADS',
    name: 'Waist Rise Western Wear',
    price: 2873,
    originalPrice: 5746,
    discount: '(50% OFF)',
    imageUrl: '/products/7158_Women_WesternWear_Jeans_WaistRise_HighRise_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in blue, featuring a striking waist rise pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p160',
    brand: 'BASICS+',
    name: 'Waist Rise Western Wear',
    price: 2926,
    originalPrice: 5852,
    discount: '(50% OFF)',
    imageUrl: '/products/7158_Women_WesternWear_Jeans_WaistRise_HighRise_blue.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking waist rise pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p161',
    brand: 'ONYX',
    name: 'Waist Rise Western Wear',
    price: 2979,
    originalPrice: 5958,
    discount: '(50% OFF)',
    imageUrl: '/products/7158_Women_WesternWear_Jeans_WaistRise_HighRise_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking waist rise pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p162',
    brand: 'FRONTIER',
    name: 'Waist Rise Western Wear',
    price: 1332,
    originalPrice: 2664,
    discount: '(50% OFF)',
    imageUrl: '/products/7159_Women_WesternWear_Jeans_WaistRise_MidRise_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in blue, featuring a striking waist rise pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p163',
    brand: 'RUSTLER CO.',
    name: 'Waist Rise Western Wear',
    price: 1385,
    originalPrice: 2770,
    discount: '(50% OFF)',
    imageUrl: '/products/7159_Women_WesternWear_Jeans_WaistRise_MidRise_blue.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking waist rise pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p164',
    brand: 'METRO UOMO',
    name: 'Waist Rise Western Wear',
    price: 1438,
    originalPrice: 2876,
    discount: '(50% OFF)',
    imageUrl: '/products/7159_Women_WesternWear_Jeans_WaistRise_MidRise_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking waist rise pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p165',
    brand: 'AURA',
    name: 'Waist Rise Western Wear',
    price: 1491,
    originalPrice: 2982,
    discount: '(50% OFF)',
    imageUrl: '/products/7160_Women_WesternWear_Jeans_WaistRise_LowRise_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in blue, featuring a striking waist rise pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p166',
    brand: 'VEXEL',
    name: 'Waist Rise Western Wear',
    price: 1544,
    originalPrice: 3088,
    discount: '(50% OFF)',
    imageUrl: '/products/7160_Women_WesternWear_Jeans_WaistRise_LowRise_blue.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking waist rise pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p167',
    brand: 'ECLAT',
    name: 'Waist Rise Western Wear',
    price: 1597,
    originalPrice: 3194,
    discount: '(50% OFF)',
    imageUrl: '/products/7160_Women_WesternWear_Jeans_WaistRise_LowRise_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking waist rise pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p168',
    brand: 'ZENITH',
    name: 'Wash Western Wear',
    price: 1650,
    originalPrice: 3300,
    discount: '(50% OFF)',
    imageUrl: '/products/7164_Women_WesternWear_Jeans_Wash_LightWash_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in blue, featuring a striking wash pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p169',
    brand: 'INDIGO THREADS',
    name: 'Wash Western Wear',
    price: 1703,
    originalPrice: 3406,
    discount: '(50% OFF)',
    imageUrl: '/products/7164_Women_WesternWear_Jeans_Wash_LightWash_blue.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking wash pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p170',
    brand: 'BASICS+',
    name: 'Wash Western Wear',
    price: 1756,
    originalPrice: 3512,
    discount: '(50% OFF)',
    imageUrl: '/products/7164_Women_WesternWear_Jeans_Wash_LightWash_grey.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in grey, featuring a striking wash pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p171',
    brand: 'ONYX',
    name: 'Wash Western Wear',
    price: 1809,
    originalPrice: 3618,
    discount: '(50% OFF)',
    imageUrl: '/products/7165_Women_WesternWear_Jeans_Wash_MidWash_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in blue, featuring a striking wash pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p172',
    brand: 'FRONTIER',
    name: 'Wash Western Wear',
    price: 1862,
    originalPrice: 3724,
    discount: '(50% OFF)',
    imageUrl: '/products/7165_Women_WesternWear_Jeans_Wash_MidWash_blue.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking wash pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p173',
    brand: 'RUSTLER CO.',
    name: 'Wash Western Wear',
    price: 1915,
    originalPrice: 3830,
    discount: '(50% OFF)',
    imageUrl: '/products/7165_Women_WesternWear_Jeans_Wash_MidWash_grey.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in grey, featuring a striking wash pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p174',
    brand: 'METRO UOMO',
    name: 'Wash Western Wear',
    price: 1968,
    originalPrice: 3936,
    discount: '(50% OFF)',
    imageUrl: '/products/7166_Women_WesternWear_Jeans_Wash_HeavyWash_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in blue, featuring a striking wash pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p175',
    brand: 'AURA',
    name: 'Wash Western Wear',
    price: 2021,
    originalPrice: 4042,
    discount: '(50% OFF)',
    imageUrl: '/products/7166_Women_WesternWear_Jeans_Wash_HeavyWash_blue.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking wash pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p176',
    brand: 'VEXEL',
    name: 'Wash Western Wear',
    price: 2074,
    originalPrice: 4148,
    discount: '(50% OFF)',
    imageUrl: '/products/7166_Women_WesternWear_Jeans_Wash_HeavyWash_grey.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in grey, featuring a striking wash pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p177',
    brand: 'ECLAT',
    name: 'Sleeve Type Western Wear',
    price: 2127,
    originalPrice: 4254,
    discount: '(50% OFF)',
    imageUrl: '/products/7180_Women_WesternWear_Top_SleeveType_Oneshouldersleeve_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking sleeve type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p178',
    brand: 'ZENITH',
    name: 'Sleeve Type Western Wear',
    price: 2180,
    originalPrice: 4360,
    discount: '(50% OFF)',
    imageUrl: '/products/7180_Women_WesternWear_Top_SleeveType_Oneshouldersleeve_red.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking sleeve type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p179',
    brand: 'INDIGO THREADS',
    name: 'Sleeve Type Western Wear',
    price: 2233,
    originalPrice: 4466,
    discount: '(50% OFF)',
    imageUrl: '/products/7180_Women_WesternWear_Top_SleeveType_Oneshouldersleeve_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in red, featuring a striking sleeve type pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p180',
    brand: 'BASICS+',
    name: 'Fit Western Wear',
    price: 2286,
    originalPrice: 4572,
    discount: '(50% OFF)',
    imageUrl: '/products/7256_Women_WesternWear_Top_Fit_AthleticFit_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p181',
    brand: 'ONYX',
    name: 'Fit Western Wear',
    price: 2339,
    originalPrice: 4678,
    discount: '(50% OFF)',
    imageUrl: '/products/7256_Women_WesternWear_Top_Fit_AthleticFit_grey.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in grey, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p182',
    brand: 'FRONTIER',
    name: 'Fit Western Wear',
    price: 2392,
    originalPrice: 4784,
    discount: '(50% OFF)',
    imageUrl: '/products/7256_Women_WesternWear_Top_Fit_AthleticFit_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p183',
    brand: 'RUSTLER CO.',
    name: 'Fit Western Wear',
    price: 2445,
    originalPrice: 4890,
    discount: '(50% OFF)',
    imageUrl: '/products/8038_Women_WesternWear_Top_Fit_BoxyFit_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in brown, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p184',
    brand: 'METRO UOMO',
    name: 'Fit Western Wear',
    price: 2498,
    originalPrice: 4996,
    discount: '(50% OFF)',
    imageUrl: '/products/8038_Women_WesternWear_Top_Fit_BoxyFit_brown.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p185',
    brand: 'AURA',
    name: 'Fit Western Wear',
    price: 2551,
    originalPrice: 5102,
    discount: '(50% OFF)',
    imageUrl: '/products/8038_Women_WesternWear_Top_Fit_BoxyFit_red.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p186',
    brand: 'VEXEL',
    name: 'Fit Western Wear',
    price: 2604,
    originalPrice: 5208,
    discount: '(50% OFF)',
    imageUrl: '/products/8038_Women_WesternWear_Top_Fit_BoxyFit_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in red, featuring a striking fit pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p187',
    brand: 'ECLAT',
    name: 'Neckline Western Wear',
    price: 2657,
    originalPrice: 5314,
    discount: '(50% OFF)',
    imageUrl: '/products/8042_Women_WesternWear_Top_Neckline_Tieup_black.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in black, featuring a striking neckline pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p188',
    brand: 'ZENITH',
    name: 'Neckline Western Wear',
    price: 2710,
    originalPrice: 5420,
    discount: '(50% OFF)',
    imageUrl: '/products/8042_Women_WesternWear_Top_Neckline_Tieup_grey.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in white, featuring a striking neckline pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p189',
    brand: 'INDIGO THREADS',
    name: 'Neckline Western Wear',
    price: 2763,
    originalPrice: 5526,
    discount: '(50% OFF)',
    imageUrl: '/products/8042_Women_WesternWear_Top_Neckline_Tieup_red.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in red, featuring a striking neckline pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'p190',
    brand: 'BASICS+',
    name: 'Neckline Western Wear',
    price: 2816,
    originalPrice: 5632,
    discount: '(50% OFF)',
    imageUrl: '/products/8042_Women_WesternWear_Top_Neckline_Tieup_white.jpg',
    gender: 'Women',
    category: 'Western Wear',
    description: 'A stylish women western wear in grey, featuring a striking neckline pattern.',
    sizes: ['S', 'M', 'L', 'XL'],
  },
];
